### ISSUE TITLE
Have I misconfigured?

### ISSUE THREAD

**Issue by pwright** [logseq/publish-spa#1]
Is there a step I'm missing.. ran it on a few graphs, always get:
```
$ logseq-publish-spa out
Error: Logseq static directory '../logseq/static' does not exist. Please provide a valid directory

```

**Comment by pwright** [comment]
btw I'm trying to run CLI to output to `out` directory, and am unsure in the README where it says to run commands in

https://github.com/logseq/publish-spa/blob/1acc2743898210f9c5218d3c33bebbed9106fb32/action.yml#L58

Where is `_logseq`?

**Comment by Bad3r** [comment]
This is a GH action you can't run it directly from the CLI.
See: https://github.com/logseq/logseq/issues/9060

**Comment by Bad3r** [comment]
> thanks @Bad3r - should this section of readme be edited to make this clear?
> 
> https://github.com/logseq/publish-spa#cli

If you want to run the action locally, you can't just run a single line without setting up the same env the action is doing. You can see that _logseq is created in the first step:
```yml
  steps:
    # First, build logseq's static/ and publishing assets
    - name: Checkout logseq
      uses: actions/checkout@v3
      with:
        repository: logseq/logseq
        path: _logseq
        ref: ${{ inputs.version }}
```
