### ISSUE TITLE
whiteboards generate error block workflow

### ISSUE THREAD

**Issue by genffy** [logseq/publish-spa#10]
### What Happened?

the raw log is [logs_21.zip](https://github.com/logseq/publish-spa/files/11683599/logs_21.zip)

The root cause is that the `whiteboard` rename has some problems, as I rename a whiteboard, it copies and renames but does not delete the old one, causing id conflict, but it does not show correctly. Issue: https://github.com/logseq/logseq/issues/9194

publish.yml
```yaml
name: logseq-publish
on: [push]

permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    steps:
      - uses: actions/checkout@v3
      - uses: logseq/publish-spa@v0.2.0
      - name: add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
```

### Reproduce the Bug

- create a whiteboard file 
- push to trigger action
- rename it
- re push 

### Expected Behavior

I want this action to catch the error, and warn it but not block it.
