### ISSUE TITLE
Publish workflow fails

### ISSUE THREAD

**Issue by HarvsG** [logseq/publish-spa#21]
### What Happened?

I tried to publish my graph:

But when the workflow ran I got this error
```
Options: {:directory ".", :static-directory ".logseq-logseq/static", :theme-mode "light", :accent-color "blue"}
Error: Invalid graph directory '/home/runner/work/logseq/logseq' as it has no logseq/config.edn.
Error: Process completed with exit code 1.
```

Similar issue

### Reproduce the Bug

- I mostly followed [[this tutorial](https://docs.logseq.com/#/page/publishing%20(desktop%20app%20only)](https://docs.logseq.com/#/page/publishing%20(desktop%20app%20only)
- Created a new public github repo https://github.com/HarvsG/logseq

- I enabled github pages

- Created a new folder `C:\Users\{user}\Documents\Coding\repositories\logseq-public`

- 3 dots -> settings -> editor -> All pages public when publishing to `off`

- Confirm at least one page is marked `public:: true`

- In logseq 3 dots -> Export Graph -> Export public pages and selected the above foler

- Inside `logseq-public` run `mkdir -p .github/workflows/ && touch .github/workflows/publish.yml`

- run `nano .github/workflows/publish.yml`

	- From https://github.com/logseq/publish-spa?tab=readme-ov-file#usage 

	  ```yaml
	  on: [push]
	  
	  permissions:
	    contents: write
	  jobs:
	    test:
	      runs-on: ubuntu-latest
	      name: Publish Logseq graph
	      steps:
	        - uses: actions/checkout@v3
	        - uses: logseq/publish-spa@v0.3.0
	        - name: Add a nojekyll file # to make sure asset paths are correctly identified
	          run: touch $GITHUB_WORKSPACE/www/.nojekyll
	        - name: Deploy 🚀
	          uses: JamesIves/github-pages-deploy-action@v4
	          with:
	            folder: www
	  ```
- Inside `logseq-public` I ran `git init`

-

  ```
  git remote add origin git@github.com:HarvsG/logseq.git
  git add *
  git commit -m "Initial commit" 
  git add .github/workflows/publish.yml
  git commit -m actions
  git branch -M main
  git push -u origin main
  ```
- In digital ocean I made  a cname record from `notes.codingdoctor.co.uk` to `harvsg.github.io.`

	- The TXT entry for `_github-pages-challenge-harvsg.codingdoctor.co.uk` was already configured from another project

- In the github pages dashboard

### Expected Behavior

The workflow runs correctly

### Desktop or Mobile Platform Information

Windows 11 desktop 0.10.3
