### ISSUE TITLE
Github Action with Cloning-with-https-urls Build Failure

### ISSUE THREAD

**Issue by jackyliu16** [logseq/publish-spa#40]
### What Happened?

When i run my Github Action by manually push to repo, the log is bellow 
(In the past, it worked normally. I didn't modify any github action files after init)
Manual update to version 0.3.1 after error occurred, but the situation did not improve。

![image](https://github.com/user-attachments/assets/f244d6c0-102e-4eb3-80d5-8954f22f3b33)

## Error Message 
```
[+] Pushing git commit
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/jackyliu16/notes.git/'
```

## Overall Profile
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: logseq/publish-spa@v0.3.1
        with: 
          output-directory: www 
      - name: Add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: www
      - name: Push to publish repos and use github pages display
        uses: jackyliu16/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'www'
          destination-github-username: 'jackyliu16'
          destination-repository-name: 'notes'
          user-email: '18922251299@163.com' 
          target-branch: master 
        #
          # git config --global user.name "jackyliu16"
          # git config --global user.email "18922251299@163.com"
          # git add .
          # git commit -m "Auto-Deploy from logseq"
          # git push https://${{ secrets.GH_TOKEN }}@github.com/jackyliu16/jackyliu16.github.io.git gh-pages
```

### Reproduce the Bug

Just push to repo.

### Expected Behavior

All CI success and update github page correctlly.

### Desktop or Mobile Platform Information

OS Version: Win11 23H2 22631.4169
Desktop Version: 0.10.9-alpha+nightly.20240528
